<?php

function sc2replays_perm()
{
    return array(   'View Replays',
                    'Add Replays'
                );
}

function sc2replays_admin()
{
    $form = array();

    
    $form['sc2replays_active'] = array(
        '#type' => 'checkbox',
        '#title' => t('Active'),
        '#default_value' => variable_get('sc2replays_active', TRUE),
        '#size' => 2,
        '#maxlength' => 2,
        '#description' => t('Is the replay system enabled?'),
        '#required' => FALSE,
    );

    $form['sc2replays_readonly'] = array(
        '#type' => 'checkbox',
        '#title' => t('Readonly'),
        '#default_value' => variable_get('sc2replays_readonly', FALSE),
        '#size' => 2,
        '#maxlength' => 2,
        '#description' => t('Are replays allowed to be uploaded to the system - or is it read only?'),
        '#required' => FALSE,
    );

    $form['sc2replays_autoparse'] = array(
        '#type' => 'checkbox',
        '#title' => t('Automatically Parse Replays'),
        '#default_value' => variable_get('sc2replays_autoparse', TRUE),
        '#size' => 2,
        '#maxlength' => 2,
        '#description' => t('Automatically parse replay information? Or force the user to enter it themselves.'),
        '#required' => FALSE,
    );
    
    $form['sc2replays_storagepath'] = array(
    
        '#type' => 'textfield',
        '#title' => 'Path to store replays',
        '#default_value' => variable_get('sc2replays_storagepath', file_directory_path()),
        '#size' => 80,
        '#description' => 'Make sure not to change this without first copying over the existing replays. Otherwise the system will die.',
        '#required' => TRUE,
    
    );
    



    return system_settings_form($form);

}

function sc2replays_menu()
{

  $items = array();

    $items['admin/settings/sc2replays'] = array(
    'title' => 'SC2Replays',
    'description' => 'Manage SC2Replays module here',
   'page callback' => 'system_settings_form',
   'page arguments' => array('sc2replays_admin'),
   'access arguments' => array('access administration pages'),
   
    'type' => MENU_NORMAL_ITEM,
   );


    $items['replay/new'] = array(
      'title' => 'Submit Replay',
      'page callback' => 'new_replay_page',
      'access arguments' => array('access content'),
      'type' => MENU_SUGGESTED_ITEM,
    );

  return $items;
}


function new_replay_page()
{
    return drupal_get_form('replays_form_new');
}


function replays_form_new($form_state)
{

    $form = array();
    $form['#attributes'] = array('enctype' => 'multipart/form-data');
    $form['file'] = array(
    
        '#type' => 'file',
        '#title' => 'Select Replay File',
        

    );
    
    $form['submit'] = array(
    
        '#type' => 'submit',
        #'#name' => 'Upload Replay',
        '#value' => 'Submit Replay',   
    
    );
    
    return $form;

}



function replays_form_new_submit($form, &$form_state)
{
    
    file_save_upload('file', array(), variable_get('sc2replays_storagepath', ''),FILE_EXISTS_RENAME);
    drupal_set_message('lets go');
}

function replays_form_new_validate($form, &$form_state)
{


}


function sc2replays_admin_validate($form, &$form_state)
{
  
}
